name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      # Không bắt buộc, nhưng giúp Oryx chọn Node 20 đúng version yêu cầu của vite/react-router 7
      - name: Set expected Node version for Oryx
        run: |
          jq '.engines = {"node":"20.x"} + .' Frontend/package.json > Frontend/package.tmp && mv Frontend/package.tmp Frontend/package.json

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_HILL_0AE64DD1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # PR comments, etc.
          action: "upload"

          ###### Repository/Build Configurations ######
          app_location: "/Frontend"   # Thư mục mã nguồn FE
          api_location: ""            # Không dùng Functions (BE tách riêng)
          output_location: "dist"     # Vite build ra dist/
          production_branch: "main"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_HILL_0AE64DD1E }}
          action: "close"
